// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBof4FRdC7J_YpWN5WcLBrMpvAei6cC3TU',
    appId: '1:57418835279:web:a6c850a291c38f6835113a',
    messagingSenderId: '57418835279',
    projectId: 'databasesapp-896df',
    authDomain: 'databasesapp-896df.firebaseapp.com',
    storageBucket: 'databasesapp-896df.appspot.com',
    measurementId: 'G-G9CD4LK1T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5d84mPq_3MDipxYaAopDwdFRnGz1sMcU',
    appId: '1:57418835279:android:be3887ed5356465935113a',
    messagingSenderId: '57418835279',
    projectId: 'databasesapp-896df',
    storageBucket: 'databasesapp-896df.appspot.com',
  );
}
